name: chattr_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment: 
  sdk: ^3.9.0-333.2.beta

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  cryptography: ^2.7.0
<<<<<<< HEAD
  shared_preferences: ^2.2.2
  http: ^1.1.0
  emoji_picker_flutter: ^1.6.3
=======
  shared_preferences: ^2.2.0
>>>>>>> e56979a (End-to-end versleuteling)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true